version: '3.8'
services:
  spring_app:
    image: krajmark/ebayclone:0.0.3
    container_name: ebayclonecompose
    depends_on:
      - mysql_database
    environment:
      MYSQL_URL: "mysql://mysql_database:3306/ebayclone?createDatabaseIfNotExist=true"
      MYSQLUSER: root
      MYSQLPASSWORD: asdasd
    ports:
      - "8082:8080"
    networks:
      - ebayclone_network
  mysql_database:
    image: mysql:latest
    container_name: mysqlcompose
    restart: always
    environment:
      MYSQL_DATABASE: ebayclone
      MYSQL_ROOT_PASSWORD: asdasd
    ports:
      - '3308:3306'
    expose:
      - '3306'
    networks:
      - ebayclone_network
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:

networks:
  ebayclone_network: