openapi: 3.0.0
info:
  version: 'TBD'
  title: 'E-Bay Clone Swagger UI - with OpenAPI 3.0'
  description: 'Having some fun with Springboot...'
  contact:
    name: KrajnyakMark
    url: https://ebayclone-production.up.railway.app/
    email: asdasd@asd.io
externalDocs:
  description: Check out the main website
  url: https://ebayclone-production.up.railway.app/
servers:
  - url: http://localhost:8080
  - url: https://ebayclone-production.up.railway.app
tags:
  - name: main
    description: Basic stuff...
#  - name: user
#    description: Operations with users
#    externalDocs:
#      description: Register as a customer on our website
#      url: https://ebayclone-production.up.railway.app/auth/register/buyer
  - name: auth
    description: User authentication
paths:
  /index:
    get:
      tags:
        - main
      summary: Some info...
      description: Will give back some about info...
      operationId: mainStuff
      responses:
        200:
          description: Successfully loaded hom page
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/EsterEgg'
  /health/check:
    get:
      tags:
        - main
      summary: Check the health of the application
      operationId: health
      responses:
        200:
          description: Successful healthcheck
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EsterEgg'
  /auth/login:
    post:
      tags:
        - auth
      summary: Authentication related endpoints
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'

      responses:
        200:
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        404:
          description:
components:
  schemas:
    EsterEgg:
      type: object
      properties:
        hi:
          type: string
        welcome:
          type: string
        credits:
          type: array
          items:
            type: string
        advice:
          type: array
          items:
            type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          required: true
          default: admin123
        password:
          type: string
          required: true
          default: asdasd
    LoginResponse:
      type: object
      properties:
        token:
          type: string
          default: I am a JWT
        balance:
          type: number
  securitySchemes:
    JWT_Auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
